In [1]:
import numpy as np

## Numpy

In [2]:
# Câu 1: A
arr = np.arange(0, 10, 1)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
# Câu 2: D
np.ones((3, 3)) > 0

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [4]:
np.full((3, 3), dtype=bool, fill_value=True)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [5]:
np.ones((3, 3), dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [6]:
# Câu 3: A
import numpy as np
arr = np.arange(0, 10)
arr[arr%2==1]

array([1, 3, 5, 7, 9])

In [7]:
# Câu 4: B
arr = np.arange(0, 10)
arr[arr%2==1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [8]:
# Câu 5: B
arr = np.arange(0, 10)
arr_2d = arr.reshape(2, -1)
arr_2d

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [9]:
# Câu 6: A
arr1 = np.arange(10).reshape(2, -1)
arr2 = np.repeat(1, 10).reshape(2, -1)
c = np.concatenate([arr1, arr2], axis=0)
c

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [10]:
# Câu 7: C
arr1 = np.arange(10).reshape(2, -1)
arr2 = np.repeat(1, 10).reshape(2, -1)
c = np.concatenate([arr1, arr2], axis=1)
c

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [11]:
# Câu 8: A
arr = np.array([1, 2, 3])
print(np.repeat(arr, 3))
print(np.tile(arr, 3))

[1 1 1 2 2 2 3 3 3]
[1 2 3 1 2 3 1 2 3]


In [12]:
# Câu 9: C
a = np.array([2, 6, 1, 9, 10, 3, 27])
index = np.where((a>=5) & (a<=10))
a[index]

array([ 6,  9, 10])

In [13]:
# Câu 10: D
def maxx(x, y):
    if x >= y:
        return x
    else:
        return y

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

pair_max = np.vectorize(maxx, otypes=[float])
pair_max(a, b)

array([6., 7., 9., 8., 9., 7., 5.])

In [14]:
# Câu 11: A
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
np.where(a<b, b, a)

array([6, 7, 9, 8, 9, 7, 5])

## Xử lý ảnh

In [15]:
import cv2

In [16]:
# Image download
!gdown 1i9dqan21DjQoG5Q_VEvm0LrVwAlXD0vB

Downloading...
From: https://drive.google.com/uc?id=1i9dqan21DjQoG5Q_VEvm0LrVwAlXD0vB
To: d:\Study\AI-Book\AIO\Module_2\week_1\dog.jpeg

  0%|          | 0.00/33.7k [00:00<?, ?B/s]
100%|██████████| 33.7k/33.7k [00:00<00:00, 614kB/s]


In [21]:
def convert2gray(vector):
    return np.max(vector) * 0.5 + np.min(vector) * 0.5

In [23]:
# Câu 12: A
import matplotlib.image as mpimg
img = mpimg.imread('D:\Study\AI-Book\AIO\Module_2\week_1\dog.jpeg')
gray_img_01 = np.apply_along_axis(convert2gray, 2, img)
gray_img_01[0, 0]

102.5

In [24]:
!gdown 1i9dqan21DjQoG5Q_VEvm0LrVwAlXD0vB

Downloading...
From: https://drive.google.com/uc?id=1i9dqan21DjQoG5Q_VEvm0LrVwAlXD0vB
To: d:\Study\AI-Book\AIO\Module_2\week_1\dog.jpeg

  0%|          | 0.00/33.7k [00:00<?, ?B/s]
100%|██████████| 33.7k/33.7k [00:00<00:00, 664kB/s]


In [25]:
# Câu 13: A
def convert2gray_avg(vector):
    return np.mean(vector)

img = mpimg.imread('D:\Study\AI-Book\AIO\Module_2\week_1\dog.jpeg')
gray_img_02 = np.apply_along_axis(convert2gray_avg, 2, img)
gray_img_02[0, 0]

107.66666666666667

In [26]:
# Câu 14: C
def convert2gray_luminosity(vector):
    return 0.21 * vector[0] + 0.72 * vector[1] + 0.07 * vector[2]
  
img = mpimg.imread('D:\Study\AI-Book\AIO\Module_2\week_1\dog.jpeg')
gray_img_03 = np.apply_along_axis(convert2gray_luminosity, 2, img)
gray_img_03[0, 0]

126.22999999999999

## Phân tích dữ liệu bảng

In [27]:
!gdown 1iA0WmVfW88HyJvTBSQDI5vesf-pgKabq

Downloading...
From: https://drive.google.com/uc?id=1iA0WmVfW88HyJvTBSQDI5vesf-pgKabq
To: d:\Study\AI-Book\AIO\Module_2\week_1\advertising.csv

  0%|          | 0.00/4.06k [00:00<?, ?B/s]
100%|██████████| 4.06k/4.06k [00:00<?, ?B/s]


In [35]:
import pandas as pd

df = pd.read_csv('D:\\Study\\AI-Book\\AIO\\Module_2\\week_1\\advertising.csv')
data = df.to_numpy()

In [42]:
# Câu 15: C
print(f'Max: {df.Sales.max()} - Index: {df.Sales.idxmax()}')

Max: 27.0 - Index: 175


In [44]:
# Câu 16: B
df['TV'].mean()

147.0425

In [46]:
# Câu 17: A
df[df['Sales']>=20].shape[0]

40

In [47]:
# Câu 18: B
df.loc[df['Sales']>=15,'Radio'].mean()

26.22293577981651

In [48]:
# Câu 19: C
df.loc[df['Newspaper']>df['Newspaper'].mean(), 'Sales'].sum()

1405.1

In [50]:
# Câu 20: C
A = df['Sales'].mean()
scores = ['Good' if ele > A else 'Bad' if ele < A else 'Average' for ele in df['Sales']]
scores[7:10]

['Bad', 'Bad', 'Good']

In [63]:
# Câu 21: C
mean = df['Sales'].mean()
A = 0
distance = 99999
for i in df['Sales']:
    if abs(i - mean) < distance:
        A = i
        distance = abs(i - mean)

scores = ['Good' if ele > A else 'Bad' if ele < A else 'Average' for ele in df['Sales']]
scores[7:10]

['Bad', 'Bad', 'Good']