### Câu hỏi 1:

In [5]:
import torch
import torch.nn as nn

data = torch.Tensor([1,2,3])
softmax_funct = nn.Softmax(dim=0)
output = softmax_funct(data)
output

tensor([0.0900, 0.2447, 0.6652])

`Answer: c) [0.0900, 0.2447, 0.6652]`

### Câu hỏi 2:

In [15]:
import torch
import torch.nn as nn

class MySoftmax(nn.Module):
  def __init__(self):
    super().__init__()
  
  def forward(self, x):
    exps = torch.exp(x)
    return exps / exps.sum()
  
data = torch.Tensor([5,2,4])
my_softmax = MySoftmax()
output = my_softmax(data)
output

tensor([0.7054, 0.0351, 0.2595])

`Answer: b) [0.7054, 0.0351, 0.2595]`

### Câu hỏi 3:

In [14]:
import torch
import torch.nn as nn

class MySoftmax(nn.Module):
  def __init__(self):
    super().__init__()
    
  def forward(self, x):
    exps = torch.exp(x)
    return exps / exps.sum()
  
data = torch.Tensor([1,2,300000000])
my_softmax = MySoftmax()
output = my_softmax(data)
output

tensor([0., 0., nan])

`Answer: c) [0., 0., nan`

### Câu hỏi 4:

In [16]:
import torch
import torch.nn as nn

class MySoftmax(nn.Module):
  def __init__(self):
    super().__init__()
    
  def forward(self, x):
    exps = torch.exp(x)
    return exps / exps.sum()
  
data = torch.Tensor([1,2,3])
my_softmax = MySoftmax()
output = my_softmax(data)
output

tensor([0.0900, 0.2447, 0.6652])

`Answer: b) [0.0900, 0.2447, 0.6652]`

### Câu hỏi 5

In [18]:
from abc import ABC , abstractmethod
class Person(ABC):
  def __init__(self , name:str , yob:int):
    self._name = name
    self._yob = yob

  def get_yob(self):
    return self._yob
  
  @abstractmethod
  def describe(self):
    pass
  
class Student(Person):
  def __init__(self, name: str, yob: int, grade: str):
    super().__init__(name, yob)
    self.grade = grade
  
  def describe(self):
    print(f'Student - Name: {self._name} - YoB: {self._yob} - Grade: {self.grade}')

student1 = Student(name='studentZ2023', yob=2011, grade=6)
student1.describe()

Student - Name: studentZ2023 - YoB: 2011 - Grade: 6


`Answer: a) Student - Name: studentZ2023 - YoB: 2011 - Grade: 6`

### Câu hỏi 6

In [19]:
from abc import ABC, abstractmethod

class Person(ABC):
  def __init__(self, name: str, yob: int) -> None:
    self._name = name
    self._yob = yob
    
  def get_yob(self):
    return self._yob
  
  @abstractmethod
  def describe(self):
    pass

class Teacher(Person):
  def __init__(self, name: str, yob: int, subject: str) -> None:
    super().__init__(name, yob)
    self._subject = subject
  
  def describe(self):
    print(f'Teacher - Name: {self._name} - YoB: {self._yob} - Subject: {self._subject}')

teacher1 = Teacher(name='teacherZ2023', yob=1991, subject="History")
teacher1.describe()

Teacher - Name: teacherZ2023 - YoB: 1991 - Subject: History


`Answer: b) Teacher - Name: teacherZ2023 - YoB: 1991 - Subject: History`

### Câu hỏi 7

In [20]:
from abc import ABC, abstractmethod

class Person(ABC):
  def __init__(self, name: str, yob: int) -> None:
    self._name = name
    self._yob = yob
    
  def get_yob(self):
    return self._yob
  
  @abstractmethod
  def describe(self):
    pass

class Doctor(Person):
  def __init__(self, name: str, yob: int, specialist: str) -> None:
    super().__init__(name, yob)
    self._specialist = specialist
  
  def describe(self):
    print(f'Doctor - Name: {self._name} - YoB: {self._yob} - Specialist: {self._specialist}')

doctor1 = Doctor(name='doctorZ2023', yob=1981, specialist='Endocrinologists')
doctor1.describe()

Doctor - Name: doctorZ2023 - YoB: 1981 - Specialist: Endocrinologists


`Answer: a) Doctor - Name: doctorZ2023 - YoB: 1981 - Specialist: Endocrinologists`

### Câu hỏi 8

In [23]:
class Ward:
  def __init__(self, name: str) -> None:
    self.__name = name
    self.__listPeople = list()
  
  def add_person(self, person: Person):
    self.__listPeople.append(person)
  
  def describe(self):
    print(f"Ward Name: {self.__name}")
    for p in self.__listPeople:
      p.describe()
      
  def count_doctor(self):
    count = 0
    for p in self.__listPeople:
      if isinstance(p, Doctor):
        count += 1
    
    return count
  
student1 = Student(name='studentA', yob=2010, grade='7')
teacher1 = Teacher(name='teacherA', yob=1969, subject="Math")
teacher2 = Teacher(name='teacherB', yob=1995, subject="History")
doctor1 = Doctor(name='doctorA', yob=1945, specialist='Endocrinologists')
doctor2 = Doctor(name='doctorB', yob=1975, specialist='Cardiologists')

ward1 = Ward(name='Ward1')
ward1.add_person(student1)
ward1.add_person(teacher1)
ward1.add_person(teacher2)
ward1.add_person(doctor1)
ward1.add_person(doctor2)
ward1.count_doctor()

2

`Answer: c) 2`

### Câu hỏi 9:

In [36]:
class MyStack:
  def __init__(self, capacity) -> None:
    self.__capacity = capacity
    self.__stack = []
    
  def is_full(self):
    return len(self.__stack) == self.__capacity

  def push(self, value):
    self.__stack = list([value, ]) + self.__stack
    
stack1 = MyStack(capacity=5)
stack1.push(1)
stack1.push(2)
print(stack1.is_full())

False


`Answer: b) False`

### Câu hỏi 10

In [38]:
class MyStack:
  def __init__(self, capacity) -> None:
    self.__capacity = capacity
    self.__stack = []
    
  def is_full(self):
    return len(self.__stack) == self.__capacity

  def push(self, value):
    self.__stack = list([value, ]) + self.__stack
    
  def top(self):
    return self.__stack[0]
    
stack1 = MyStack(capacity=5)
stack1.push(1)
stack1.push(2)
stack1.top()

2

`Answer: b) 2`

### Câu hỏi 11

In [39]:
class MyQueue:
  def __init__(self, capacity) -> None:
    self.__capacity = capacity
    self.__queue = []
    
  def is_full(self):
    return len(self.__queue) == self.__capacity

  def enqueue(self, value):
    self.__queue.append(value)
    
queue1 = MyQueue(capacity=5)
queue1.enqueue(1)
queue1.enqueue(2)
print(queue1.is_full())

False


`Answer: a) False`

### Câu hỏi 12

In [41]:
class MyQueue:
  def __init__(self, capacity) -> None:
    self.__capacity = capacity
    self.__queue = []
    
  def is_full(self):
    return len(self.__queue) == self.__capacity

  def enqueue(self, value):
    self.__queue.append(value)
    
  def front(self):
    return self.__queue[0]
    
queue1 = MyQueue(capacity=5)
queue1.enqueue(1)
queue1.enqueue(2)
print(queue1.front())

1


`Answer: d) 1`